name: Build and Release .NET App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish Linux
        run: |
          OUT_DIR=./release_output/linux-x64
          dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o $OUT_DIR
          zip -r app-linux-x64.zip $OUT_DIR

      - name: Build and Publish Windows
        run: |
          OUT_DIR=./release_output/win-x64
          dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o $OUT_DIR
          zip -r app-win-x64.zip $OUT_DIR

      - name: Build and Publish macOS
        run: |
          OUT_DIR=./release_output/osx-x64
          dotnet publish -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true -o $OUT_DIR
          zip -r app-osx-x64.zip $OUT_DIR

      - name: Create Tag
        if: github.ref == 'refs/heads/main'
        run: |
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.run_number }} \
            --title="Build v${{ github.run_number }}" \
            --generate-notes \
            ./app-linux-x64.zip \
            ./app-win-x64.zip \
            ./app-osx-x64.zip
